namespace: prod

configMapGenerator:
- name: psdmcalibconfigs
  literals:
  - CALIBDB_URL_FILE=/work/secrets/calibdb_url
  - ROLEDB_URL_FILE=/work/secrets/roledb_url
  - JWKS_URI=https://psdm.slac.stanford.edu/pcdstkn/keys
  - LOG_LEVEL=DEBUG

generatorOptions:
  disableNameSuffixHash: true

bases:
- ../../base

images:
- name: psdmcalib
  newName: cr.stanford.edu/psdm/psdm_k8s_images/slaclab/psdmcalib
  newTag: 0.0.3
- name: psdmcalibapache
  newName: cr.stanford.edu/psdm/psdm_k8s_images/slaclab/psweb_kerb
  newTag: 0.0.5
- name: pcdsrvpxjwt
  newName: cr.stanford.edu/psdm/psdm_k8s_images/slaclab/pcdsrvpxjwt
  newTag: 0.0.1

secretGenerator:
- name: psdmcalib-secrets
  files:
  - etc/.secrets/keytab
  - etc/.secrets/calibdb_url
  - etc/.secrets/roledb_url

patches:
  - target:
      kind: Deployment
      name: psdmcalib
    patch: |
      - op: replace
        path: /spec/replicas
        value: 4

patchesJson6902:
- target:
    kind: Ingress
    name: psdmcalibingress-open
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: pswww.slac.stanford.edu
- target:
    kind: Ingress
    name: psdmcalibingress-kerb
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: pswww.slac.stanford.edu
- target:
    kind: Ingress
    name: psdmcalibingress-jwt
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: pswww.slac.stanford.edu
